// Auto generated by Craby. DO NOT EDIT.
// Hash: 7c9e0bb7a8635032
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait ZedIconsSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn get_icon_svg(&mut self, name: &str) -> String;
    fn list_icons(&mut self) -> String;
}

pub trait ZedLlmSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn emit(&self, signal_name: ZedLLMSignal) {
        let manager = crate::ffi::bridging::get_signal_manager();
        match signal_name {
            ZedLLMSignal::AcpThreadsChanged(data) => {
                let signal = Box::new(ZedLLMSignal::AcpThreadsChanged(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "acpThreadsChanged", signal_ptr);
                }
            }
            ZedLLMSignal::AgentConnected(data) => {
                let signal = Box::new(ZedLLMSignal::AgentConnected(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "agentConnected", signal_ptr);
                }
            }
            ZedLLMSignal::AgentDisconnected(data) => {
                let signal = Box::new(ZedLLMSignal::AgentDisconnected(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "agentDisconnected", signal_ptr);
                }
            }
            ZedLLMSignal::LlmChunk(data) => {
                let signal = Box::new(ZedLLMSignal::LlmChunk(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "llmChunk", signal_ptr);
                }
            }
            ZedLLMSignal::LlmDone(data) => {
                let signal = Box::new(ZedLLMSignal::LlmDone(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "llmDone", signal_ptr);
                }
            }
            ZedLLMSignal::LlmError(data) => {
                let signal = Box::new(ZedLLMSignal::LlmError(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "llmError", signal_ptr);
                }
            }
            ZedLLMSignal::ThreadSnapshot(data) => {
                let signal = Box::new(ZedLLMSignal::ThreadSnapshot(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "threadSnapshot", signal_ptr);
                }
            }
            ZedLLMSignal::ToolCallEvent(data) => {
                let signal = Box::new(ZedLLMSignal::ToolCallEvent(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "toolCallEvent", signal_ptr);
                }
            }
        }
    }
    fn add_listener(&mut self, event_name: &str) -> Void;
    fn cancel_request(&mut self, request_id: Number) -> Void;
    fn cancel_tool_call(&mut self, tool_call_id: &str) -> Boolean;
    fn connect_agent(&mut self, agent_type: &str) -> Boolean;
    fn disconnect_agent(&mut self, agent_type: &str) -> Void;
    fn ensure_agent_thread(&mut self, agent_type: &str) -> Boolean;
    fn get_agent_models(&mut self, agent_type: &str) -> String;
    fn get_agent_modes(&mut self, agent_type: &str) -> String;
    fn get_agent_servers(&mut self) -> String;
    fn get_default_model_id(&mut self) -> String;
    fn get_models(&mut self) -> String;
    fn get_providers(&mut self) -> String;
    fn is_available(&mut self) -> Boolean;
    fn list_acp_threads(&mut self) -> String;
    fn minimize_chat_pane(&mut self) -> Void;
    fn open_acp_thread(&mut self, thread_id: &str) -> Boolean;
    fn remove_listeners(&mut self, count: Number) -> Void;
    fn respond_to_tool_authorization(&mut self, tool_call_id: &str, permission_option_id: &str) -> Boolean;
    fn search_acp_threads(&mut self, query: &str) -> String;
    fn send_message(&mut self, message: &str) -> Number;
    fn send_message_to_agent(&mut self, agent_type: &str, message: &str) -> Number;
    fn send_message_to_model(&mut self, model_id: &str, message: &str) -> Number;
    fn set_agent_mode(&mut self, agent_type: &str, mode_id: &str) -> Boolean;
    fn set_agent_model(&mut self, agent_type: &str, model_id: &str) -> Boolean;
    fn set_chat_pane_visible(&mut self, visible: Boolean) -> Void;
    fn start_agent_thread(&mut self, agent_type: &str) -> Boolean;
}

pub enum ZedLLMSignal {
    AcpThreadsChanged(AcpThreadsChangedEvent),
    AgentConnected(AgentConnectedEvent),
    AgentDisconnected(AgentDisconnectedEvent),
    LlmChunk(LLMChunkEvent),
    LlmDone(LLMDoneEvent),
    LlmError(LLMErrorEvent),
    ThreadSnapshot(ThreadSnapshotPayload),
    ToolCallEvent(ToolCallEventEvent),
}

pub trait ZedMarkdownSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn parse(&mut self, markdown: &str) -> String;
}

pub trait ZedThemeSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn emit(&self, signal_name: ZedThemeSignal) {
        let manager = crate::ffi::bridging::get_signal_manager();
        match signal_name {
            ZedThemeSignal::ThemeChanged(data) => {
                let signal = Box::new(ZedThemeSignal::ThemeChanged(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "themeChanged", signal_ptr);
                }
            }
        }
    }
    fn add_listener(&mut self, event_name: &str) -> Void;
    fn get_color(&mut self, name: &str) -> Nullable<String>;
    fn get_theme(&mut self) -> ThemeData;
    fn remove_listeners(&mut self, count: Number) -> Void;
}

pub enum ZedThemeSignal {
    ThemeChanged(ThemeChangedEvent),
}

pub trait ZedWorkspaceSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn emit(&self, signal_name: ZedWorkspaceSignal) {
        let manager = crate::ffi::bridging::get_signal_manager();
        match signal_name {
            ZedWorkspaceSignal::WorkspaceChanged(data) => {
                let signal = Box::new(ZedWorkspaceSignal::WorkspaceChanged(data));
                let signal_ptr = Box::into_raw(signal) as usize;
                unsafe {
                    manager.emit(self.id(), "workspaceChanged", signal_ptr);
                }
            }
        }
    }
    fn add_listener(&mut self, event_name: &str) -> Void;
    fn get_workspace_info(&mut self) -> WorkspaceInfo;
    fn remove_listeners(&mut self, count: Number) -> Void;
}

pub enum ZedWorkspaceSignal {
    WorkspaceChanged(WorkspaceChangedEvent),
}

impl Default for NullableString {
    fn default() -> Self {
        NullableString {
            null: true,
            val: String::default(),
        }
    }
}

impl From<NullableString> for Nullable<String> {
    fn from(val: NullableString) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<String>> for NullableString {
    fn from(val: Nullable<String>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableString {
            val: val.unwrap_or(String::default()),
            null,
        }
    }
}

impl Default for LLMErrorEvent {
    fn default() -> Self {
        LLMErrorEvent {
            request_id: 0.0,
            error: String::default()
        }
    }
}

impl Default for AgentDisconnectedEvent {
    fn default() -> Self {
        AgentDisconnectedEvent {
            agent_type: String::default(),
            reason: String::default()
        }
    }
}

impl Default for LLMChunkEvent {
    fn default() -> Self {
        LLMChunkEvent {
            request_id: 0.0,
            chunk: String::default()
        }
    }
}

impl Default for AcpThreadsChangedEvent {
    fn default() -> Self {
        AcpThreadsChangedEvent {
            threads: String::default()
        }
    }
}

impl Default for AgentConnectedEvent {
    fn default() -> Self {
        AgentConnectedEvent {
            agent_type: String::default(),
            session_id: String::default()
        }
    }
}

impl Default for ThemeData {
    fn default() -> Self {
        ThemeData {
            name: String::default(),
            appearance: String::default(),
            colors: ThemeColors::default(),
            fonts: FontSettings::default()
        }
    }
}

impl Default for ThemeColors {
    fn default() -> Self {
        ThemeColors {
            background: String::default(),
            surface_background: String::default(),
            elevated_surface_background: String::default(),
            panel_background: String::default(),
            element_background: String::default(),
            element_hover: String::default(),
            element_active: String::default(),
            element_selected: String::default(),
            element_disabled: String::default(),
            ghost_element_background: String::default(),
            ghost_element_hover: String::default(),
            ghost_element_active: String::default(),
            ghost_element_selected: String::default(),
            text: String::default(),
            text_muted: String::default(),
            text_placeholder: String::default(),
            text_disabled: String::default(),
            text_accent: String::default(),
            icon: String::default(),
            icon_muted: String::default(),
            icon_disabled: String::default(),
            icon_accent: String::default(),
            border: String::default(),
            border_variant: String::default(),
            border_focused: String::default(),
            border_selected: String::default(),
            border_disabled: String::default(),
            tab_bar_background: String::default(),
            tab_active_background: String::default(),
            tab_inactive_background: String::default(),
            status_bar_background: String::default(),
            title_bar_background: String::default(),
            toolbar_background: String::default(),
            scrollbar_thumb_background: String::default()
        }
    }
}

impl Default for ThreadSnapshotPayload {
    fn default() -> Self {
        ThreadSnapshotPayload {
            snapshot: String::default()
        }
    }
}

impl Default for FontSettings {
    fn default() -> Self {
        FontSettings {
            ui_font_family: String::default(),
            ui_font_size: 0.0,
            buffer_font_family: String::default(),
            buffer_font_size: 0.0
        }
    }
}

impl Default for WorkspaceInfo {
    fn default() -> Self {
        WorkspaceInfo {
            project_name: NullableString::default(),
            root_path: NullableString::default(),
            current_file_path: NullableString::default()
        }
    }
}

impl Default for ThemeChangedEvent {
    fn default() -> Self {
        ThemeChangedEvent {
            theme: ThemeData::default()
        }
    }
}

impl Default for WorkspaceChangedEvent {
    fn default() -> Self {
        WorkspaceChangedEvent {
            workspace: WorkspaceInfo::default()
        }
    }
}

impl Default for LLMDoneEvent {
    fn default() -> Self {
        LLMDoneEvent {
            request_id: 0.0
        }
    }
}

impl Default for ToolCallEventEvent {
    fn default() -> Self {
        ToolCallEventEvent {
            event: String::default()
        }
    }
}
