// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use rngpui_craby::prelude::*;

use crate::zed_icons_impl::*;
use crate::zed_llm_impl::*;
use crate::zed_markdown_impl::*;
use crate::zed_theme_impl::*;
use crate::zed_workspace_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::zedmodules::bridging")]
pub mod bridging {
    #[derive(Clone)]
    struct AcpThreadsChangedEvent {
        threads: String,
    }

    #[derive(Clone)]
    struct AgentConnectedEvent {
        agent_type: String,
        session_id: String,
    }

    #[derive(Clone)]
    struct AgentDisconnectedEvent {
        agent_type: String,
        reason: String,
    }

    #[derive(Clone)]
    struct FontSettings {
        ui_font_family: String,
        ui_font_size: f64,
        buffer_font_family: String,
        buffer_font_size: f64,
    }

    #[derive(Clone)]
    struct LLMChunkEvent {
        request_id: f64,
        chunk: String,
    }

    #[derive(Clone)]
    struct LLMDoneEvent {
        request_id: f64,
    }

    #[derive(Clone)]
    struct LLMErrorEvent {
        request_id: f64,
        error: String,
    }

    #[derive(Clone)]
    struct NullableString {
        null: bool,
        val: String,
    }

    #[derive(Clone)]
    struct ThemeChangedEvent {
        theme: ThemeData,
    }

    #[derive(Clone)]
    struct ThemeColors {
        background: String,
        surface_background: String,
        elevated_surface_background: String,
        panel_background: String,
        element_background: String,
        element_hover: String,
        element_active: String,
        element_selected: String,
        element_disabled: String,
        ghost_element_background: String,
        ghost_element_hover: String,
        ghost_element_active: String,
        ghost_element_selected: String,
        text: String,
        text_muted: String,
        text_placeholder: String,
        text_disabled: String,
        text_accent: String,
        icon: String,
        icon_muted: String,
        icon_disabled: String,
        icon_accent: String,
        border: String,
        border_variant: String,
        border_focused: String,
        border_selected: String,
        border_disabled: String,
        tab_bar_background: String,
        tab_active_background: String,
        tab_inactive_background: String,
        status_bar_background: String,
        title_bar_background: String,
        toolbar_background: String,
        scrollbar_thumb_background: String,
    }

    #[derive(Clone)]
    struct ThemeData {
        name: String,
        appearance: String,
        colors: ThemeColors,
        fonts: FontSettings,
    }

    #[derive(Clone)]
    struct ThreadSnapshotPayload {
        snapshot: String,
    }

    #[derive(Clone)]
    struct ToolCallEventEvent {
        event: String,
    }

    #[derive(Clone)]
    struct WorkspaceChangedEvent {
        workspace: WorkspaceInfo,
    }

    #[derive(Clone)]
    struct WorkspaceInfo {
        project_name: NullableString,
        root_path: NullableString,
        current_file_path: NullableString,
    }

    extern "Rust" {
        type ZedIcons;

        type ZedLlm;

        type ZedMarkdown;

        type ZedTheme;

        type ZedWorkspace;

        #[cxx_name = "createZedIcons"]
        fn create_zed_icons(id: usize, data_path: &str) -> Box<ZedIcons>;

        #[cxx_name = "getIconSvg"]
        fn zed_icons_get_icon_svg(it_: &mut ZedIcons, name: &str) -> Result<String>;

        #[cxx_name = "listIcons"]
        fn zed_icons_list_icons(it_: &mut ZedIcons) -> Result<String>;

        #[cxx_name = "createZedLlm"]
        fn create_zed_llm(id: usize, data_path: &str) -> Box<ZedLlm>;

        #[cxx_name = "addListener"]
        fn zed_llm_add_listener(it_: &mut ZedLlm, event_name: &str) -> Result<()>;

        #[cxx_name = "cancelRequest"]
        fn zed_llm_cancel_request(it_: &mut ZedLlm, request_id: f64) -> Result<()>;

        #[cxx_name = "cancelToolCall"]
        fn zed_llm_cancel_tool_call(it_: &mut ZedLlm, tool_call_id: &str) -> Result<bool>;

        #[cxx_name = "connectAgent"]
        fn zed_llm_connect_agent(it_: &mut ZedLlm, agent_type: &str) -> Result<bool>;

        #[cxx_name = "disconnectAgent"]
        fn zed_llm_disconnect_agent(it_: &mut ZedLlm, agent_type: &str) -> Result<()>;

        #[cxx_name = "ensureAgentThread"]
        fn zed_llm_ensure_agent_thread(it_: &mut ZedLlm, agent_type: &str) -> Result<bool>;

        #[cxx_name = "getAgentModels"]
        fn zed_llm_get_agent_models(it_: &mut ZedLlm, agent_type: &str) -> Result<String>;

        #[cxx_name = "getAgentModes"]
        fn zed_llm_get_agent_modes(it_: &mut ZedLlm, agent_type: &str) -> Result<String>;

        #[cxx_name = "getAgentServers"]
        fn zed_llm_get_agent_servers(it_: &mut ZedLlm) -> Result<String>;

        #[cxx_name = "getDefaultModelId"]
        fn zed_llm_get_default_model_id(it_: &mut ZedLlm) -> Result<String>;

        #[cxx_name = "getModels"]
        fn zed_llm_get_models(it_: &mut ZedLlm) -> Result<String>;

        #[cxx_name = "getProviders"]
        fn zed_llm_get_providers(it_: &mut ZedLlm) -> Result<String>;

        #[cxx_name = "isAvailable"]
        fn zed_llm_is_available(it_: &mut ZedLlm) -> Result<bool>;

        #[cxx_name = "listAcpThreads"]
        fn zed_llm_list_acp_threads(it_: &mut ZedLlm) -> Result<String>;

        #[cxx_name = "minimizeChatPane"]
        fn zed_llm_minimize_chat_pane(it_: &mut ZedLlm) -> Result<()>;

        #[cxx_name = "openAcpThread"]
        fn zed_llm_open_acp_thread(it_: &mut ZedLlm, thread_id: &str) -> Result<bool>;

        #[cxx_name = "removeListeners"]
        fn zed_llm_remove_listeners(it_: &mut ZedLlm, count: f64) -> Result<()>;

        #[cxx_name = "respondToToolAuthorization"]
        fn zed_llm_respond_to_tool_authorization(it_: &mut ZedLlm, tool_call_id: &str, permission_option_id: &str) -> Result<bool>;

        #[cxx_name = "searchAcpThreads"]
        fn zed_llm_search_acp_threads(it_: &mut ZedLlm, query: &str) -> Result<String>;

        #[cxx_name = "sendMessage"]
        fn zed_llm_send_message(it_: &mut ZedLlm, message: &str) -> Result<f64>;

        #[cxx_name = "sendMessageToAgent"]
        fn zed_llm_send_message_to_agent(it_: &mut ZedLlm, agent_type: &str, message: &str) -> Result<f64>;

        #[cxx_name = "sendMessageToModel"]
        fn zed_llm_send_message_to_model(it_: &mut ZedLlm, model_id: &str, message: &str) -> Result<f64>;

        #[cxx_name = "setAgentMode"]
        fn zed_llm_set_agent_mode(it_: &mut ZedLlm, agent_type: &str, mode_id: &str) -> Result<bool>;

        #[cxx_name = "setAgentModel"]
        fn zed_llm_set_agent_model(it_: &mut ZedLlm, agent_type: &str, model_id: &str) -> Result<bool>;

        #[cxx_name = "setChatPaneVisible"]
        fn zed_llm_set_chat_pane_visible(it_: &mut ZedLlm, visible: bool) -> Result<()>;

        #[cxx_name = "startAgentThread"]
        fn zed_llm_start_agent_thread(it_: &mut ZedLlm, agent_type: &str) -> Result<bool>;

        #[cxx_name = "createZedMarkdown"]
        fn create_zed_markdown(id: usize, data_path: &str) -> Box<ZedMarkdown>;

        #[cxx_name = "parse"]
        fn zed_markdown_parse(it_: &mut ZedMarkdown, markdown: &str) -> Result<String>;

        #[cxx_name = "createZedTheme"]
        fn create_zed_theme(id: usize, data_path: &str) -> Box<ZedTheme>;

        #[cxx_name = "addListener"]
        fn zed_theme_add_listener(it_: &mut ZedTheme, event_name: &str) -> Result<()>;

        #[cxx_name = "getColor"]
        fn zed_theme_get_color(it_: &mut ZedTheme, name: &str) -> Result<NullableString>;

        #[cxx_name = "getTheme"]
        fn zed_theme_get_theme(it_: &mut ZedTheme) -> Result<ThemeData>;

        #[cxx_name = "removeListeners"]
        fn zed_theme_remove_listeners(it_: &mut ZedTheme, count: f64) -> Result<()>;

        #[cxx_name = "createZedWorkspace"]
        fn create_zed_workspace(id: usize, data_path: &str) -> Box<ZedWorkspace>;

        #[cxx_name = "addListener"]
        fn zed_workspace_add_listener(it_: &mut ZedWorkspace, event_name: &str) -> Result<()>;

        #[cxx_name = "getWorkspaceInfo"]
        fn zed_workspace_get_workspace_info(it_: &mut ZedWorkspace) -> Result<WorkspaceInfo>;

        #[cxx_name = "removeListeners"]
        fn zed_workspace_remove_listeners(it_: &mut ZedWorkspace, count: f64) -> Result<()>;
    }

    extern "Rust" {
        type ZedLLMSignal;
        fn get_acp_threads_changed_payload(s: &ZedLLMSignal) -> AcpThreadsChangedEvent;
        fn get_agent_connected_payload(s: &ZedLLMSignal) -> AgentConnectedEvent;
        fn get_agent_disconnected_payload(s: &ZedLLMSignal) -> AgentDisconnectedEvent;
        fn get_llm_chunk_payload(s: &ZedLLMSignal) -> LLMChunkEvent;
        fn get_llm_done_payload(s: &ZedLLMSignal) -> LLMDoneEvent;
        fn get_llm_error_payload(s: &ZedLLMSignal) -> LLMErrorEvent;
        fn get_thread_snapshot_payload(s: &ZedLLMSignal) -> ThreadSnapshotPayload;
        fn get_tool_call_event_payload(s: &ZedLLMSignal) -> ToolCallEventEvent;
        unsafe fn drop_zed_llm_signal(signal: *mut ZedLLMSignal);
        type ZedThemeSignal;
        fn get_theme_changed_payload(s: &ZedThemeSignal) -> ThemeChangedEvent;
        unsafe fn drop_zed_theme_signal(signal: *mut ZedThemeSignal);
        type ZedWorkspaceSignal;
        fn get_workspace_changed_payload(s: &ZedWorkspaceSignal) -> WorkspaceChangedEvent;
        unsafe fn drop_zed_workspace_signal(signal: *mut ZedWorkspaceSignal);
    }

    #[namespace = "craby::zedmodules::signals"]
    unsafe extern "C++" {
        include!("CrabySignals.h");

        type SignalManager;

        // Use usize as a type-erased pointer since signals from different modules have different types
        unsafe fn emit(self: &SignalManager, id: usize, name: &str, signal: usize);

        #[rust_name = "get_signal_manager"]
        fn getSignalManager() -> &'static SignalManager;
    }
}

fn create_zed_icons(id: usize, data_path: &str) -> Box<ZedIcons> {
    let ctx = Context::new(id, data_path);
    Box::new(ZedIcons::new(ctx))
}

fn zed_icons_get_icon_svg(it_: &mut ZedIcons, name: &str) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_icon_svg(name);
        ret
    })
}

fn zed_icons_list_icons(it_: &mut ZedIcons) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.list_icons();
        ret
    })
}

fn create_zed_llm(id: usize, data_path: &str) -> Box<ZedLlm> {
    let ctx = Context::new(id, data_path);
    Box::new(ZedLlm::new(ctx))
}

fn zed_llm_add_listener(it_: &mut ZedLlm, event_name: &str) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.add_listener(event_name);
        ret
    })
}

fn zed_llm_cancel_request(it_: &mut ZedLlm, request_id: f64) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.cancel_request(request_id);
        ret
    })
}

fn zed_llm_cancel_tool_call(it_: &mut ZedLlm, tool_call_id: &str) -> Result<bool, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.cancel_tool_call(tool_call_id);
        ret
    })
}

fn zed_llm_connect_agent(it_: &mut ZedLlm, agent_type: &str) -> Result<bool, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.connect_agent(agent_type);
        ret
    })
}

fn zed_llm_disconnect_agent(it_: &mut ZedLlm, agent_type: &str) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.disconnect_agent(agent_type);
        ret
    })
}

fn zed_llm_ensure_agent_thread(it_: &mut ZedLlm, agent_type: &str) -> Result<bool, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.ensure_agent_thread(agent_type);
        ret
    })
}

fn zed_llm_get_agent_models(it_: &mut ZedLlm, agent_type: &str) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_agent_models(agent_type);
        ret
    })
}

fn zed_llm_get_agent_modes(it_: &mut ZedLlm, agent_type: &str) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_agent_modes(agent_type);
        ret
    })
}

fn zed_llm_get_agent_servers(it_: &mut ZedLlm) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_agent_servers();
        ret
    })
}

fn zed_llm_get_default_model_id(it_: &mut ZedLlm) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_default_model_id();
        ret
    })
}

fn zed_llm_get_models(it_: &mut ZedLlm) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_models();
        ret
    })
}

fn zed_llm_get_providers(it_: &mut ZedLlm) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_providers();
        ret
    })
}

fn zed_llm_is_available(it_: &mut ZedLlm) -> Result<bool, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.is_available();
        ret
    })
}

fn zed_llm_list_acp_threads(it_: &mut ZedLlm) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.list_acp_threads();
        ret
    })
}

fn zed_llm_minimize_chat_pane(it_: &mut ZedLlm) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.minimize_chat_pane();
        ret
    })
}

fn zed_llm_open_acp_thread(it_: &mut ZedLlm, thread_id: &str) -> Result<bool, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.open_acp_thread(thread_id);
        ret
    })
}

fn zed_llm_remove_listeners(it_: &mut ZedLlm, count: f64) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.remove_listeners(count);
        ret
    })
}

fn zed_llm_respond_to_tool_authorization(it_: &mut ZedLlm, tool_call_id: &str, permission_option_id: &str) -> Result<bool, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.respond_to_tool_authorization(tool_call_id, permission_option_id);
        ret
    })
}

fn zed_llm_search_acp_threads(it_: &mut ZedLlm, query: &str) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.search_acp_threads(query);
        ret
    })
}

fn zed_llm_send_message(it_: &mut ZedLlm, message: &str) -> Result<f64, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.send_message(message);
        ret
    })
}

fn zed_llm_send_message_to_agent(it_: &mut ZedLlm, agent_type: &str, message: &str) -> Result<f64, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.send_message_to_agent(agent_type, message);
        ret
    })
}

fn zed_llm_send_message_to_model(it_: &mut ZedLlm, model_id: &str, message: &str) -> Result<f64, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.send_message_to_model(model_id, message);
        ret
    })
}

fn zed_llm_set_agent_mode(it_: &mut ZedLlm, agent_type: &str, mode_id: &str) -> Result<bool, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.set_agent_mode(agent_type, mode_id);
        ret
    })
}

fn zed_llm_set_agent_model(it_: &mut ZedLlm, agent_type: &str, model_id: &str) -> Result<bool, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.set_agent_model(agent_type, model_id);
        ret
    })
}

fn zed_llm_set_chat_pane_visible(it_: &mut ZedLlm, visible: bool) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.set_chat_pane_visible(visible);
        ret
    })
}

fn zed_llm_start_agent_thread(it_: &mut ZedLlm, agent_type: &str) -> Result<bool, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.start_agent_thread(agent_type);
        ret
    })
}

fn create_zed_markdown(id: usize, data_path: &str) -> Box<ZedMarkdown> {
    let ctx = Context::new(id, data_path);
    Box::new(ZedMarkdown::new(ctx))
}

fn zed_markdown_parse(it_: &mut ZedMarkdown, markdown: &str) -> Result<String, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.parse(markdown);
        ret
    })
}

fn create_zed_theme(id: usize, data_path: &str) -> Box<ZedTheme> {
    let ctx = Context::new(id, data_path);
    Box::new(ZedTheme::new(ctx))
}

fn zed_theme_add_listener(it_: &mut ZedTheme, event_name: &str) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.add_listener(event_name);
        ret
    })
}

fn zed_theme_get_color(it_: &mut ZedTheme, name: &str) -> Result<NullableString, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_color(name);
        ret.into()
    })
}

fn zed_theme_get_theme(it_: &mut ZedTheme) -> Result<ThemeData, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_theme();
        ret
    })
}

fn zed_theme_remove_listeners(it_: &mut ZedTheme, count: f64) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.remove_listeners(count);
        ret
    })
}

fn create_zed_workspace(id: usize, data_path: &str) -> Box<ZedWorkspace> {
    let ctx = Context::new(id, data_path);
    Box::new(ZedWorkspace::new(ctx))
}

fn zed_workspace_add_listener(it_: &mut ZedWorkspace, event_name: &str) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.add_listener(event_name);
        ret
    })
}

fn zed_workspace_get_workspace_info(it_: &mut ZedWorkspace) -> Result<WorkspaceInfo, anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.get_workspace_info();
        ret
    })
}

fn zed_workspace_remove_listeners(it_: &mut ZedWorkspace, count: f64) -> Result<(), anyhow::Error> {
    rngpui_craby::catch_panic!({
        let ret = it_.remove_listeners(count);
        ret
    })
}

fn get_acp_threads_changed_payload(s: &ZedLLMSignal) -> AcpThreadsChangedEvent {
    match s {
        ZedLLMSignal::AcpThreadsChanged(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_acp_threads_changed_payload"),
    }
}

fn get_agent_connected_payload(s: &ZedLLMSignal) -> AgentConnectedEvent {
    match s {
        ZedLLMSignal::AgentConnected(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_agent_connected_payload"),
    }
}

fn get_agent_disconnected_payload(s: &ZedLLMSignal) -> AgentDisconnectedEvent {
    match s {
        ZedLLMSignal::AgentDisconnected(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_agent_disconnected_payload"),
    }
}

fn get_llm_chunk_payload(s: &ZedLLMSignal) -> LLMChunkEvent {
    match s {
        ZedLLMSignal::LlmChunk(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_llm_chunk_payload"),
    }
}

fn get_llm_done_payload(s: &ZedLLMSignal) -> LLMDoneEvent {
    match s {
        ZedLLMSignal::LlmDone(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_llm_done_payload"),
    }
}

fn get_llm_error_payload(s: &ZedLLMSignal) -> LLMErrorEvent {
    match s {
        ZedLLMSignal::LlmError(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_llm_error_payload"),
    }
}

fn get_thread_snapshot_payload(s: &ZedLLMSignal) -> ThreadSnapshotPayload {
    match s {
        ZedLLMSignal::ThreadSnapshot(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_thread_snapshot_payload"),
    }
}

fn get_tool_call_event_payload(s: &ZedLLMSignal) -> ToolCallEventEvent {
    match s {
        ZedLLMSignal::ToolCallEvent(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_tool_call_event_payload"),
    }
}

unsafe fn drop_zed_llm_signal(signal: *mut ZedLLMSignal) {
    if !signal.is_null() {
        drop(Box::from_raw(signal));
    }
}

fn get_theme_changed_payload(s: &ZedThemeSignal) -> ThemeChangedEvent {
    match s {
        ZedThemeSignal::ThemeChanged(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_theme_changed_payload"),
    }
}

unsafe fn drop_zed_theme_signal(signal: *mut ZedThemeSignal) {
    if !signal.is_null() {
        drop(Box::from_raw(signal));
    }
}

fn get_workspace_changed_payload(s: &ZedWorkspaceSignal) -> WorkspaceChangedEvent {
    match s {
        ZedWorkspaceSignal::WorkspaceChanged(payload) => (*payload).clone(),
        _ => panic!("Invalid signal type for get_workspace_changed_payload"),
    }
}

unsafe fn drop_zed_workspace_signal(signal: *mut ZedWorkspaceSignal) {
    if !signal.is_null() {
        drop(Box::from_raw(signal));
    }
}
