// Auto generated by Craby. DO NOT EDIT.
#pragma once

// Craby Desktop Registration
// Auto-generated - do not edit

#include "CxxZedIconsModule.hpp"
#include "CxxZedLlmModule.hpp"
#include "CxxZedMarkdownModule.hpp"
#include "CxxZedThemeModule.hpp"
#include "CxxZedWorkspaceModule.hpp"
#include <ReactCommon/TurboModule.h>
#include <ReactCommon/CallInvoker.h>
#include <memory>
#include <string>

namespace craby {
namespace zedmodules {
namespace registration {

/// Set the data path for all Craby modules.
/// Call this before registerModules().
inline void setDataPath(const std::string& dataPath) {
  craby::zedmodules::modules::CxxZedIconsModule::dataPath = dataPath;
  craby::zedmodules::modules::CxxZedLlmModule::dataPath = dataPath;
  craby::zedmodules::modules::CxxZedMarkdownModule::dataPath = dataPath;
  craby::zedmodules::modules::CxxZedThemeModule::dataPath = dataPath;
  craby::zedmodules::modules::CxxZedWorkspaceModule::dataPath = dataPath;
}

/// Register all Craby modules with the provided registry.
/// Template allows integration with any TurboModuleRegistry type.
/// The registry must support: registry.emplace(name, EntryType{devOnly, factory})
template<typename TurboModuleRegistry>
inline void registerModules(
    TurboModuleRegistry& registry,
    std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
  using Entry = typename TurboModuleRegistry::mapped_type;
  registry.emplace("ZedIcons", Entry{
    false,
    [jsInvoker] {
      return std::make_shared<craby::zedmodules::modules::CxxZedIconsModule>(jsInvoker);
    }
  });
  registry.emplace("ZedLLM", Entry{
    false,
    [jsInvoker] {
      return std::make_shared<craby::zedmodules::modules::CxxZedLlmModule>(jsInvoker);
    }
  });
  registry.emplace("ZedMarkdown", Entry{
    false,
    [jsInvoker] {
      return std::make_shared<craby::zedmodules::modules::CxxZedMarkdownModule>(jsInvoker);
    }
  });
  registry.emplace("ZedTheme", Entry{
    false,
    [jsInvoker] {
      return std::make_shared<craby::zedmodules::modules::CxxZedThemeModule>(jsInvoker);
    }
  });
  registry.emplace("ZedWorkspace", Entry{
    false,
    [jsInvoker] {
      return std::make_shared<craby::zedmodules::modules::CxxZedWorkspaceModule>(jsInvoker);
    }
  });
}

} // namespace registration
} // namespace zedmodules
} // namespace craby
