// Auto generated by Craby. DO NOT EDIT.
#include "CxxZedIconsModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace zedmodules {
namespace modules {

std::string CxxZedIconsModule::dataPath = std::string();

CxxZedIconsModule::CxxZedIconsModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxZedIconsModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::zedmodules::bridging::ZedIcons>(
    craby::zedmodules::bridging::createZedIcons(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::zedmodules::bridging::ZedIcons *ptr) { rust::Box<craby::zedmodules::bridging::ZedIcons>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::zedmodules::utils::ThreadPool>(10);
  methodMap_["getIconSvg"] = MethodMetadata{1, &CxxZedIconsModule::getIconSvg};
  methodMap_["listIcons"] = MethodMetadata{0, &CxxZedIconsModule::listIcons};
}

CxxZedIconsModule::~CxxZedIconsModule() {
  invalidate();
}

void CxxZedIconsModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxZedIconsModule::getIconSvg(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxZedIconsModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::zedmodules::bridging::getIconSvg(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::zedmodules::utils::errorMessage(err));
  }
}

jsi::Value CxxZedIconsModule::listIcons(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxZedIconsModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::zedmodules::bridging::listIcons(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::zedmodules::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace zedmodules
} // namespace craby
