// Auto generated by Craby. DO NOT EDIT.
#include "CxxZedMarkdownModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace zedmodules {
namespace modules {

std::string CxxZedMarkdownModule::dataPath = std::string();

CxxZedMarkdownModule::CxxZedMarkdownModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxZedMarkdownModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::zedmodules::bridging::ZedMarkdown>(
    craby::zedmodules::bridging::createZedMarkdown(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::zedmodules::bridging::ZedMarkdown *ptr) { rust::Box<craby::zedmodules::bridging::ZedMarkdown>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::zedmodules::utils::ThreadPool>(10);
  methodMap_["parse"] = MethodMetadata{1, &CxxZedMarkdownModule::parse};
}

CxxZedMarkdownModule::~CxxZedMarkdownModule() {
  invalidate();
}

void CxxZedMarkdownModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxZedMarkdownModule::parse(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxZedMarkdownModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::zedmodules::bridging::parse(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::zedmodules::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace zedmodules
} // namespace craby
