// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "CrabyUtils.hpp"
#include "ffi.rs.h"
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>
#include <memory>

namespace craby {
namespace zedmodules {
namespace modules {

class JSI_EXPORT CxxZedIconsModule : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "ZedIcons";
  static std::string dataPath;

  CxxZedIconsModule(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);
  ~CxxZedIconsModule();

  void invalidate();
  static facebook::jsi::Value
  getIconSvg(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  listIcons(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
  std::shared_ptr<craby::zedmodules::bridging::ZedIcons> module_;
  std::atomic<bool> invalidated_{false};
  std::atomic<size_t> nextListenerId_{0};
  std::mutex listenersMutex_;
  std::unordered_map<
    std::string,
    std::unordered_map<size_t, std::shared_ptr<facebook::jsi::Function>>>
    listenersMap_;
  std::shared_ptr<craby::zedmodules::utils::ThreadPool> threadPool_;
};

} // namespace modules
} // namespace zedmodules
} // namespace craby
